# Generated by Django 3.2.5 on 2021-07-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_trailer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='trailer_link',
            field=models.URLField(max_length=30000),
        ),
    ]
