# Generated by Django 3.2.5 on 2021-07-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_trailer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
