# Generated by Django 3.2.5 on 2021-07-28 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='trailer_link',
        ),
    ]
