# Generated by Django 3.2.5 on 2021-07-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_profile_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='link',
            field=models.URLField(blank=True, default=1, max_length=250),
            preserve_default=False,
        ),
    ]
