# Generated by Django 3.2.5 on 2021-07-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20210729_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='game',
            new_name='forum',
        ),
    ]
