# Generated by Django 3.2.5 on 2021-07-29 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_remove_answers_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_forum', to='games.forum'),
        ),
    ]
