# Generated by Django 3.2.5 on 2021-07-29 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_auto_20210729_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='forum',
        ),
        migrations.AddField(
            model_name='profile',
            name='forum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_forum', to='games.forum'),
        ),
    ]
