# Generated by Django 3.2.5 on 2021-07-29 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_auto_20210729_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.query'),
        ),
    ]
